# Generated by Django 5.1.15 on 2026-08-13 21:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
            ],
            options={
                'verbose_name': 'type de document',
                'verbose_name_plural': 'types de document',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32, unique=True, verbose_name='référence')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='date du document')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='date d’archivage')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archivée')], default='ACTIVE', max_length=16, verbose_name='statut')),
                ('confidentiality_level', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Interne'), ('CONFIDENTIAL', 'Confidentiel')], default='INTERNAL', max_length=16, verbose_name='niveau de confidentialité')),
                ('file_size', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='taille du fichier (octets)')),
                ('checksum', models.CharField(blank=True, help_text='Empreinte SHA-256 hexadécimale, renseignée par un futur ticket d’upload.', max_length=64, verbose_name='empreinte SHA-256')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mise à jour le')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_archives', to=settings.AUTH_USER_MODEL, verbose_name='ajoutée par')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archives', to='archives.category', verbose_name='catégorie')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archives', to='archives.documenttype', verbose_name='type de document')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archives', to='archives.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'archive',
                'verbose_name_plural': 'archives',
                'ordering': ('reference',),
                'indexes': [models.Index(fields=['status', 'document_date'], name='archives_status_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'ARCHIVED'])), name='archives_archive_status_is_valid'), models.CheckConstraint(condition=models.Q(('confidentiality_level__in', ['PUBLIC', 'INTERNAL', 'CONFIDENTIAL'])), name='archives_archive_confidentiality_is_valid'), models.CheckConstraint(condition=models.Q(('file_size__gte', 0)), name='archives_archive_file_size_nonnegative'), models.CheckConstraint(condition=models.Q(('checksum', ''), ('checksum__regex', '^[0-9A-Fa-f]{64}$'), _connector='OR'), name='archives_archive_checksum_is_sha256_or_empty')],
            },
        ),
    ]
