# Generated by Django 5.1.15 on 2026-08-14 06:41

import archives.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='file',
            field=models.FileField(blank=True, help_text='Document stocké hors de toute exposition publique.', storage=archives.storage.PrivateArchiveStorage(), upload_to=archives.storage.archive_private_upload_to, verbose_name='fichier privé'),
        ),
    ]
