# Generated by Django 5.1.15 on 2026-08-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_avatar',
            field=models.BinaryField(blank=True, null=True, verbose_name='avatar privé'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_avatar_content_type',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='type MIME de l’avatar'),
        ),
    ]
