# Generated by Django 5.1.15 on 2026-08-16 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_avatar_user_profile_avatar_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureImprovementVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('SEARCH_OCR', 'Recherche enrichie et OCR'), ('SIGNATURE', 'Validation et signature électronique'), ('RETENTION', 'Calendrier de conservation'), ('ANALYTICS', 'Indicateurs et rapports'), ('SECURITY', 'Sécurité renforcée'), ('CONNECTORS', 'Connecteurs métier')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_improvement_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vote pour une amélioration future',
                'verbose_name_plural': 'votes pour les améliorations futures',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'feature'), name='accounts_unique_future_improvement_vote')],
            },
        ),
    ]
