# Generated by Django 5.1.15 on 2026-08-14 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0002_archive_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_identifier', models.CharField(max_length=150, verbose_name='identifiant acteur')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion réussie'), ('LOGOUT', 'Déconnexion'), ('ARCHIVE_CREATE', 'Création d’archive'), ('ARCHIVE_UPDATE', 'Modification d’archive'), ('ARCHIVE_VIEW', 'Consultation d’archive'), ('ARCHIVE_DOWNLOAD', 'Téléchargement d’archive')], max_length=32, verbose_name='action')),
                ('archive_reference', models.CharField(blank=True, max_length=100, verbose_name='référence archive')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='horodatage')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='adresse IP')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='détails minimaux')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='acteur')),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='archives.archive', verbose_name='archive')),
            ],
            options={
                'verbose_name': 'événement d’audit',
                'verbose_name_plural': 'événements d’audit',
                'ordering': ['-timestamp', '-pk'],
            },
        ),
    ]
