# Generated by Django 5.1.15 on 2026-08-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion réussie'), ('LOGOUT', 'Déconnexion'), ('ARCHIVE_CREATE', 'Création d’archive'), ('ARCHIVE_UPDATE', 'Modification d’archive'), ('ARCHIVE_VIEW', 'Consultation d’archive'), ('ARCHIVE_DOWNLOAD', 'Téléchargement d’archive'), ('ARCHIVE_INTEGRITY_CHECK', 'Vérification d’intégrité')], max_length=32, verbose_name='action'),
        ),
    ]
